### ISSUE TITLE
form bind cleanups object and changes it to array

### ISSUE THREAD

**Issue by markoffk** [vegas-cmf/forms#9]
Hi.

When i passing such object:
{
    "mailing_settings" : {
        "retrieval_email" : {
            "content" : ""
        }
    }
}
after binding it transforms to:
{
    "mailing_settings" : []
}

Notice, that also type was changed from {} to [].

**Comment by arius86** [comment]
Should be fixed now. Please test.

**Comment by markoffk** [comment]
I can confirm that bug does not appear in vegas-cmf/forms v1.0.6
